name: Deploy idCards-ai

on:
  push:
    branches:
      - devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            echo "==> Moving to project directory"
            cd ~/Dits-AI/idCards-ai

            echo "==> Pulling latest changes from devops branch"
            # git reset --hard
            # git clean -fd
            git fetch origin
            git checkout devops 
            git pull origin devops

            echo "==> Stopping and removing existing container if running"
            docker stop idcardsai || true
            docker rm idcardsai || true

            echo "==> Building new Docker image"
            docker build -t idcardsai .

            echo "==> Running container"
            docker run -d -p 83:80 --name idcardsai idcardsai

            echo "==> Deployment complete"
